CREATE DATABASE HELPDESK;

GO

USE HELPDESK;

GO

CREATE TABLE CLIENTES (
	PK_CLI INT PRIMARY KEY NOT NULL IDENTITY,
	NOME_CLI VARCHAR(200) NOT NULL,

	CPF_CLI VARCHAR(50),
	CNPJ_CLI VARCHAR(50),
	EMAIL_CLI VARCHAR(30),
	SENHA_CLI VARCHAR(20),
	DATA_CLI DATETIME NOT NULL,
	PK_PERCLI INT,
	PK_TELCLI INT,
	PK_ENDCLI INT
);

GO

CREATE TABLE PERFILCLIENTES (
	PK_PERCLI INT PRIMARY KEY NOT NULL IDENTITY,
	TIPO_PERCLI BIT
);

GO

CREATE TABLE TELEFONECLIENTES (
	PK_TEL_CLI INT PRIMARY KEY NOT NULL IDENTITY,
	TIPO_TELCLI CHAR(3),
	DDD_TELCLI INT,
	NUM_TELCLI INT
);

GO

CREATE TABLE ENDERECOCLIENTES (
	PK_ENDCLI INT PRIMARY KEY NOT NULL IDENTITY,
	LOGRADOURO_ENDCLI VARCHAR(50),
    CIDADE_ENDCLI VARCHAR(50),
    NUM_ENDCLI VARCHAR (20),
	BAIRRO_ENDCLI VARCHAR(20),
	CEP_ENDCLI INT,
	PK_PAISEND INT,
	PK_UFEND INT
);

GO

CREATE TABLE PAISENDERECOS (
	PK_PAISEND INT PRIMARY KEY NOT NULL IDENTITY,
	NOME_PAISEND VARCHAR(20)
);

GO

CREATE TABLE UFENDERECOS (
	PK_UFEND INT PRIMARY KEY NOT NULL IDENTITY,
	NOME_UFEND VARCHAR(20)
);

GO

CREATE TABLE CHAMADOS (
	PK_CHAM INT PRIMARY KEY	 NOT NULL IDENTITY,
	NUMERO_CHAM INT NOT NULL,
	MENS_CHAM VARCHAR(500),
	DESC_CHAM VARCHAR(500),
	ANEXO_CHAM VARCHAR(2000),
	DATA_CHAM DATETIME NOT NULL,
	PK_CLI INT,
	PK_EQUIP INT,
);

GO

CREATE TABLE COMENTARIOS (
	PK_COM INT PRIMARY KEY NOT NULL IDENTITY,
	DESC_COM VARCHAR(500),
	DATA_COM DATE,
	PK_OP_COM INT,
	PK_CHAM INT
);

GO

CREATE TABLE MARCAS (
	PK_MARCA INT PRIMARY KEY NOT NULL IDENTITY,
	DESC_MARCA VARCHAR(200)
);

GO

CREATE TABLE MODELOS (
	PK_MODELO INT PRIMARY KEY NOT NULL IDENTITY,
	DESC_MODELO VARCHAR(200)
);

GO

CREATE TABLE OPERADORCHAMADOS (
	PK_OP_CHAM INT PRIMARY KEY NOT NULL IDENTITY,
	STS_OP_CHAM VARCHAR(20) NOT NULL,
	PK_OP INT,
	PK_CHAM INT
);

GO

CREATE TABLE OPERADORES (
	PK_OP INT PRIMARY KEY NOT NULL IDENTITY,
	NOME_OP VARCHAR(30) NOT NULL,
	NUMCAD_OP INT NOT NULL,
	SENHA_OP VARCHAR(8) NOT NULL,
	TIPO_OP VARCHAR(10),
	DATA_OP DATETIME NOT NULL,
	PK_TELOP INT
);

GO

CREATE TABLE TELEFONEOPERADORES(
	PK_TELOP INT PRIMARY KEY NOT NULL IDENTITY,
	TIPO_TELOP CHAR(3),
	DDD_TELOP INT,
	NUM_TELOP BIGINT
);

GO

CREATE TABLE EQUIPAMENTOS (
	PK_EQUIP INT PRIMARY KEY NOT NULL IDENTITY,
	IDENTIFICACAO_EQUIP VARCHAR(20) NOT NULL,
	DATA_VENDA_EQUIP DATETIME NOT NULL,
	PK_CLI INT,
	PK_MODELO INT,
	PK_MARCA INT
);

GO

ALTER TABLE CLIENTES ADD CONSTRAINT FK_PERCLI FOREIGN KEY (PK_PERCLI) REFERENCES PERFILCLIENTES;
ALTER TABLE CLIENTES ADD CONSTRAINT FK_TELCLI FOREIGN KEY (PK_TELCLI) REFERENCES TELEFONECLIENTES;
ALTER TABLE CLIENTES ADD CONSTRAINT FK_ENDCLI FOREIGN KEY (PK_ENDCLI) REFERENCES ENDERECOCLIENTES;

GO

ALTER TABLE ENDERECOCLIENTES ADD CONSTRAINT FK_PAISEND FOREIGN KEY (PK_PAISEND) REFERENCES PAISENDERECOS (PK_PAISEND);
ALTER TABLE ENDERECOCLIENTES ADD CONSTRAINT FK_UFEND FOREIGN KEY (PK_UFEND) REFERENCES UFENDERECOS (PK_UFEND);

GO

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CLI FOREIGN KEY (PK_CLI) REFERENCES CLIENTES (PK_CLI);
ALTER TABLE CHAMADOS ADD CONSTRAINT FK_EQUP FOREIGN KEY (PK_EQUIP) REFERENCES EQUIPAMENTOS (PK_EQUIP);

GO

ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_CHAM FOREIGN KEY (PK_CHAM) REFERENCES CHAMADOS (PK_CHAM);
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_OP_COM FOREIGN KEY (PK_OP_COM) REFERENCES OPERADORES (PK_OP);

GO

ALTER TABLE OPERADORCHAMADOS ADD CONSTRAINT FK_OP FOREIGN KEY (PK_OP)  REFERENCES OPERADORES (PK_OP);
ALTER TABLE OPERADORCHAMADOS ADD CONSTRAINT FK_CHAM_CHAMADO FOREIGN KEY (PK_CHAM) REFERENCES CHAMADOS (PK_CHAM);

GO

ALTER TABLE OPERADORES ADD CONSTRAINT FK_TELOP FOREIGN KEY (PK_TELOP) REFERENCES TELEFONEOPERADORES (PK_TELOP);

GO

ALTER TABLE EQUIPAMENTOS ADD CONSTRAINT FK_CLI_EQUIP FOREIGN KEY (PK_CLI) REFERENCES CLIENTES (PK_CLI);
ALTER TABLE EQUIPAMENTOS ADD CONSTRAINT FK_MARCA_EQUIP FOREIGN KEY (PK_MARCA) REFERENCES MARCAS (PK_MARCA);
ALTER TABLE EQUIPAMENTOS ADD CONSTRAINT FK_MODELO_EQUIP FOREIGN KEY (PK_MODELO) REFERENCES MODELOS (PK_MODELO);

GO

INSERT INTO UFENDERECOS VALUES('AC');
INSERT INTO UFENDERECOS VALUES('AL');
INSERT INTO UFENDERECOS VALUES('AM');
INSERT INTO UFENDERECOS VALUES('AP');
INSERT INTO UFENDERECOS VALUES('BA');
INSERT INTO UFENDERECOS VALUES('CE');
INSERT INTO UFENDERECOS VALUES('DF');
INSERT INTO UFENDERECOS VALUES('ES');
INSERT INTO UFENDERECOS VALUES('GO');
INSERT INTO UFENDERECOS VALUES('MA');
INSERT INTO UFENDERECOS VALUES('MG');
INSERT INTO UFENDERECOS VALUES('MS');
INSERT INTO UFENDERECOS VALUES('MT');
INSERT INTO UFENDERECOS VALUES('PA');
INSERT INTO UFENDERECOS VALUES('PB');
INSERT INTO UFENDERECOS VALUES('PE');
INSERT INTO UFENDERECOS VALUES('PI');
INSERT INTO UFENDERECOS VALUES('PR');
INSERT INTO UFENDERECOS VALUES('RJ');
INSERT INTO UFENDERECOS VALUES('RN');
INSERT INTO UFENDERECOS VALUES('RO');
INSERT INTO UFENDERECOS VALUES('RR');
INSERT INTO UFENDERECOS VALUES('RS');
INSERT INTO UFENDERECOS VALUES('SC');
INSERT INTO UFENDERECOS VALUES('SE');
INSERT INTO UFENDERECOS VALUES('SP');
INSERT INTO UFENDERECOS VALUES('TO');

GO

INSERT INTO TELEFONEOPERADORES VALUES ('C', 11, 41310000);

GO 

INSERT INTO OPERADORES VALUES ('GERENTE INICIAL', 102030, 102030, 'G', GETDATE(), 1) ;

GO

INSERT INTO PAISENDERECOS VALUES ('Brasil')

GO

INSERT INTO PERFILCLIENTES VALUES (0);

GO


